stages:
  - test

test:
  stage: test
  before_script:
    - bundle install
    - sudo pip install -r test-requirements.txt
    - gitshelf install
  script:
    - kitchen test
  after_script:
    - kitchen destroy all
