stages:
  - test

test:
  stage: test
  before_script:
    - bundle install
    - sudo pip install -r test-requirements.txt
    - gitshelf install
  script:
    - kitchen test
  after_script:
    - kitchen destroy all

pylint:
  stage: test
  before_script:
    - sudo pip install -r test-requirements.txt
  script:
    - pylint --rcfile=.pylintrc --disable=W1307,str-format-in-logging _modules _states
